[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "vite"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://site-fournisseurs.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[build.environment]
  NODE_VERSION = "18"
